all_scraper/all_scraper/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('naver/', include('naver_scraper.urls')),
    path('admin/', admin.site.urls),
]

all_scraper/naver_scraper/urls.py
from django.urls import path

from . import views

app_name='naver_scraper'
urlpatterns=[
        path('', views.index, name='index'),
        path('crawling/', views.crawling, name='naver_crawling'),
        ]

all_scraper/naver_scraper/models.py
from django.db import models

# Create your models here.

##############Value######################

##SearchCondition class
##pk: auto-generated primary key
##keyword: keyword of crawler
##ds: start date, DateField.
##de: end date, DateField.
##search_mode: condition flag, 0 is subject only search, 1is subject+body search, IntegerField.
##press_code: code of newspaper press, CharField. In Naver, each press searching condition have their code. Daily newspaper press codes are
##1032, 1005, 2312, 1020, 2385, 1021, 1081, 1022, 2268, 1023, 1025, 1028, 1469
## and each codes are matched press name below:
## gyunghyang, kookmin, naeil, donga, maeil, munhwa, seoul, saegyae, asiatoday, josun, joongang, hangyurae, hankook
##comment: press informations are sent to server through cooke: news_office_checked=1032, 1005, 2312, ... If cookie have no news_office_checked, server will searching all news without press condition.
##essential_word: essential_word is for detailed search-'+' should be written in front of essential word, CharField
##exact_word: exact_word is for detailed search-it should be written between "". CharField
##except_word: except_word is for detailed search-'-' should be written in front of excepting word, CharField

##SearchResult class
##pk: auto-generated primary key
##news_subject: subject of news, CharField
##news_date: date of news published, DateField.
##news_press: press company of news, CharField.
##news_url: url of news published, CharField.
##news_body: body of news, CharField.
#################################################

from django.db import models

class SearchCondition(models.Model):
    key_word=models.CharField(max_length=500)
    ds=models.DateField('start date')
    de=models.DateField('end date')
    press_codes=models.CharField(max_length=500)
    search_mode=models.IntegerField()
    essential_word=models.CharField(max_length=200)
    exact_word=models.CharField(max_length=200)
    except_word=models.CharField(max_length=200)
    
    def __init__(self):
        print('SearchCondition instance created')


class SearchResult(models.Model):
    search_condition=models.ForeignKey(SearchCondition, on_delete=models.CASCADE)
    news_subject=models.CharField(max_length=1000)
    news_date=models.DateField('news published date')
    news_press=models.CharField(max_length=100)
    news_url=models.CharField(max_length=2000)
    news_body=models.CharField(max_length=100000)

all_scraper/naver_scraper/views.py
from django.http import HttpResponse
from django.shortcuts import render
from datetime import datetime

from .models import SearchCondition

from .Urllist_server import Urllist
from .file_integrate_server import filter

from .Naver_crawler_server import Naver_crawler
from .Naver_crawler_server import Naver_scraper
from .Naver_crawler_server import Naver_datasaver
import Urlmake_server

def index(request):
    return render(request, 'naver_scraper/index.html')
    
def crawling(request):
    condition=SearchCondition()
    
    condition.key_word=request.POST['key_word']
    condition.essential_word=request.POST['essential_word']
    condition.exact_word=request.POST['exact_word']
    condition.except_word=request.POST['except_word']
    
    if request.POST['ds']:
        condition.ds=datetime.strptime(request.POST['ds'], "%Y-%m-%d")
    else:
        condition.ds=datetime.strptime('2000-01-01', "%Y-%m-%d")
        
    if request.POST['de']:
        condition.de=datetime.strptime(request.POST['de'], "%Y-%m-%d")
    else:
        condition.de=datetime.today()
    
    condition.press_codes=request.POST['press_codes']
    condition.search_mode=request.POST['search_mode']
    
    gend_url=url_make(condition)
    
    list_instance=Urllist()
    crawler=Naver_crawler()
    scraper=Naver_scraper()
    saver=Naver_datasaver()
    
    list_instance.url_changer(gend_url, condtion.ds, condition.de)
    
    
    
    return HttpResponse(gend_url)
    
    
    
    

all_scraper/naver_scraper/templates/naver_scraper/index.html
<h1>네이버 크롤러/스크래퍼에 오신 것을 환영합니다!</h1>
    <form action="{% url 'naver_scraper:naver_crawling' %}" method="post"}>
    {% csrf_token %}
        <ul>
            <li>
                검색어
                <input type="search" name="key_word" id="key_word" />
                <input type="submit" value="검색">
            </li>
            <li>
                정확어
                <input type="search" name="essential_word" id="essential_word" />
            </li>
            <li>
                필수어
                <input type="search" name="exact_word" id="exact_word" />
            </li>
            <li>
                제외어
                <input type="search" name="except_word" id="except_word" />
            </li>
            <li>
                시작일
                <input type="date" name="ds" id="ds" />
                ~
                종료일
                <input type="date" name="de" id="de"  />
            </li>
            <li>
                언론사
                <input type="radio" name="press_codes" id="whole_press" value="whole_press"/><label for="whole_press">전체언론사</label>
            
                <input type="radio" name="press_codes" id="daily_press" value="daily_press" checked='checked' /><label for="daily_press">종합주간지</label>
            </li>
            <li>
                검색 모드
                <input type="radio" name="search_mode" id="all_thing" value="all_thing" checked="checked" /><label for="all_thing">제목과 본문</label>
                
                <input type="radio" name="search_mode" id="just_subject" value="just_subject" /><label for="just_subject">제목만</label>
            </li>
        </ul>
    </form>
    <p>현재 커스터마이징의 한계로, 종합주간지 기능만 지원합니다.</p>